# see: https://itnext.io/go-continuous-integration-with-travis-ci-and-docker-4b26379e54b7
#
stages:
  - test
  - deploy

jobs:
  include:
    # run linters
    - stage: test
      language: python
      python:
        - "3.9"
      services:
        - docker
      install:
        - pip install -r ./kanji-keywords/backend/requirements.txt
      script: 
        - mypy ./kanji-keywords/backend/main.py
        - (cd kanji-keywords/backend/ && python -m unittest)

    # push docker image
    - stage: deploy
      language: elm
      python:
        - "3.9"
      services:
        - docker
      install:
        - (cd kanji-keywords/frontend/ && elm make src/Main.elm)
        - docker build -f kanji-keywords/Dockerfile --no-cache --tag temachpool/kanji-keywords:${TRAVIS_COMMIT} ./kanji-keywords/
      script: 
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker push temach/kanji-keywords:${TRAVIS_COMMIT}
        - docker logout
