# see: https://itnext.io/go-continuous-integration-with-travis-ci-and-docker-4b26379e54b7
#
stages:
  - test
  - deploy

language: python
python:
  - "3.9"
services:
  - docker

jobs:
  include:
    # run linters
    - stage: test
      install:
        - pip install -r ./kanji-keywords/backend/requirements.txt
      script: 
        - mypy ./kanji-keywords/backend/main.py
        - cd kanji-keywords/backend/ && python -m unittest

    # run smoke test
    - stage: test
      install:
        - pip install -r ./kanji-keywords/backend/requirements.txt
        - find .
        - python ./kanji-keywords/backend/main.py &
      script: 
        - curl 127.0.0.1:9000

    # build docker image and smoke test it
    - stage: test
      install:
        - docker build -f kanji-keywords/Dockerfile --no-cache --tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} kanji-keywords
        - docker run -d -p 127.0.0.1:9000:9000 ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
      script: 
        - curl 127.0.0.1:9000

    # push docker image
    - stage: deploy
      install:
        - docker build -f kanji-keywords/Dockerfile --no-cache --tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} kanji-keywords
      script: 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
        - docker logout
