version: "3.6"
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/etc/letsencrypt/:/etc/letsencrypt/:ro"

  kanjikeywords:
    image: temachpool/kanji-keywords
    volumes:
      - "kanji-keywords-database:/root/kanji-keywords.db"

volumes:
  kanji-keywords-database:

